service: unsplash-proxy

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'prod'}
  timeout: 20
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: !GetAtt unsplash.Arn
  environment:
    UNSPLASH_ID: ${ssm:/resplash/key/id}

functions:
  url:
    handler: src/handler.url
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{any+}
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  serverless-offline:
    httpPort: 7000
    noPrependStageInUrl: true
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      host: localhost
      port: 8000
      migrate: true

resources:
  Resources:
    unsplash:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: unsplash
        AttributeDefinitions:
          - AttributeName: query
            AttributeType: S
        KeySchema:
          - AttributeName: query
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
